language: go

go: "1.10"

env:
  - GO_ENV=test DB_URL="mongodb://127.0.0.1:27017" BROKER_URL="tcp://192.168.72.1:1883"

services:
  - mongodb
  - docker

go_import_path: github.com/I1820/pm

before_install:
  - PKGS=$(go list ./... ) # All the import paths
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh # go dep
  - go get -u golang.org/x/lint/golint   # linter
  - go get -u github.com/kisielk/errcheck     # errcheck checks that you checked errors.

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - dep ensure
  - ./runme.sh # setups docker network and pulls required images

  # docker services
  - docker run -p 1883:1883 -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" --name vernemq1 -d erlio/docker-vernemq

before_script:
  - buffalo task mongo

script:
  - go vet -v $PKGS                   # go vet is the official Go static analyzer
  - errcheck -verbose $PKGS           # Check for unchecked errors
  - golint -set_exit_status $PKGS     # One last linter
  - buffalo test
