language: go

go: "1.10"

env:
  - GO_ENV=test DB_URL="mongodb://127.0.0.1:27017"

services:
  - mongodb

go_import_path: github.com/I1820/dm

before_install:
  - PKGS=$(go list ./... ) # All the import paths
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh # go dep
  - go get -u github.com/golang/lint/golint   # linter
  - go get -u github.com/kisielk/errcheck     # errcheck checks that you checked errors.

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - dep ensure

before_script:
  #  - buffalo task mongo
  - mongo i1820 init.js # mongo mock database

script:
  - go vet -v $PKGS                   # go vet is the official Go static analyzer
  - errcheck -verbose $PKGS           # Check for unchecked errors
  - golint -set_exit_status $PKGS     # One last linter
  - buffalo test
