sudo: required

services:
  - mongodb
  - docker

env:
  - GO_ENV=test

go_import_path: github.com/I1820/link

language: go
go: "1.10"

before_install:
  # setup some env variables
  - GO_FILES=$(find . -iname '*.go' )  # All the .go files

  # setup dependency management tool
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

  # install linters
  - go get -u github.com/golang/lint/golint     # Linter
  - go get -u github.com/kisielk/errcheck       # errcheck checks that you checked errors.

  # docker services
  - docker run -p 1883:1883 -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" --name vernemq1 -d erlio/docker-vernemq

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - dep ensure

script:
  - go vet -v $PKGS                   # go vet is the official Go static analyzer
  - errcheck -verbose $PKGS           # Check for unchecked errors
  - golint -set_exit_status $PKGS     # One last linter
  - buffalo test
